[build]
command = "yarn workspace lintme-ui build"
publish = "apps/lintme-ui/dist"

[dev]
command = "yarn workspace lintme-ui dev"
targetPort = 5173
port = 8888
framework = "vite"
publish = "apps/lintme-ui"
autoLaunch = true

# special case: render README
[[redirects]]
  from = "/readme.md"
  to = "/readme.html"
  status = 200

# fallback for everything else (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
