services:
  - type: web
    name: lintme-backend
    env: node
    rootDir: packages/backend
    buildCommand: yarn install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
